- name: Fish
  hosts: localhost
  vars:
    user: lennart
  vars_files:
    - vars/main.yml
  roles:
    - { role: dotfiles, tags: dotfiles }
    - { role: fish, tags: fish }
    - { role: i3, tags: i3 }
    - { role: pyenv, tags: pyenv }
    - { role: packages, tags: packages }
    - { role: links, tags: links }
    - { role: neovim, tags: neovim }
    - { role: matplotlib, tags: matplotlib }
    - { role: tmux, tags: tmux }

