- name: Ensure all configured dotfiles are links.
  command: "ls -F {{ item.dest }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ links }}"
  when: force == True

- name: Remove existing dotfiles file if a replacement is being linked.
  ansible.builtin.file:
    path: "{{ links[item.0].dest }}"
    state: absent
  when: "'@' not in item.1.stdout and force == True"
  with_indexed_items: "{{ existing_dotfile_info.results }}"
  when: force == True

- name: Setup links
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: link
      #    owner: "{{ ansible_user_id }}"
      #    group: "{{ ansible_user_id }}"
      #    mode: "{{ item.mode|default ('0644') }}"
    force: "{{ force }}"
  become: false
  with_items: "{{ links }}"
